apiVersion: v1
kind: Service
metadata:
  name: test-service-external
  namespace: devtest
  labels:
    app: hello-app-drv-py-1
    version: v3.0.6
spec:
  type: LoadBalancer
  selector:
    app: hello-app-drv-py-1
    version: v3.0.6
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
